apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: chathuratd007/notification-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NOTIFICATION_MONGODB_URI
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_BROKER
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SENDGRID_API_KEY
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TWILIO_ACCOUNT_SID
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TWILIO_AUTH_TOKEN
        - name: TWILIO_PHONE_NUMBER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TWILIO_PHONE_NUMBER
        - name: SUPPORT_EMAIL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SUPPORT_EMAIL
        - name: NOTIFICATION_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NOTIFICATION_API_KEY