apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: food-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: mongodb-uri
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: stripe-secret-key
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: api-key