apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
type: Opaque
data:
  payhere-merchant-id: <base64-encoded-merchant-id>
  payhere-secret: <base64-encoded-secret>
  api-key: <base64-encoded-api-key>