apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: notification-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: mongo-uri
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: kafka-broker
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: notification-secrets
              key: sendgrid-api-key
        - name: FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: notification-secrets
              key: from-email
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: notification-secrets
              key: twilio-account-sid
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: notification-secrets
              key: twilio-auth-token
        - name: TWILIO_PHONE_NUMBER
          valueFrom:
            secretKeyRef:
              name: notification-secrets
              key: twilio-phone-number
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: notification-secrets
              key: api-key