apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
type: Opaque
data:
  sendgrid-api-key: base64_encoded_sendgrid_api_key
  from-email: base64_encoded_from_email
  twilio-account-sid: base64_encoded_twilio_account_sid
  twilio-auth-token: base64_encoded_twilio_auth_token
  twilio-phone-number: base64_encoded_twilio_phone_number
  api-key: base64_encoded_api_key